//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.R", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola Guardián,.
        /// </summary>
        internal static string Cartel1t1 {
            get {
                return ResourceManager.GetString("Cartel1t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALAR SILVERLIGHT.
        /// </summary>
        internal static string Cartel1t10 {
            get {
                return ResourceManager.GetString("Cartel1t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estás a punto de convertirte en Guardián!.
        /// </summary>
        internal static string Cartel1t11 {
            get {
                return ResourceManager.GetString("Cartel1t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedo instalarlo, pero quiero participar.
        /// </summary>
        internal static string Cartel1t12 {
            get {
                return ResourceManager.GetString("Cartel1t12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si usas Chrome 45, Microsoft Edge o estás accediendo con un smartphone / tablet, por favor ayudanos probando el preview de.
        /// </summary>
        internal static string Cartel1t2 {
            get {
                return ResourceManager.GetString("Cartel1t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , sino seguí las instrucciones para instalar Silverlight!.
        /// </summary>
        internal static string Cartel1t3 {
            get {
                return ResourceManager.GetString("Cartel1t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía estamos desarrollando esta última versión que usa las tecnologías web más avanzadas que proveerá una experiencia superior en todos los navegadores, teléfonos móviles y tablets. 
        ///
        ///Tu feedback nos ayudara mejorar la nueva plataforma, después de probar, por favor completa nuestra.
        /// </summary>
        internal static string Cartel1t4 {
            get {
                return ResourceManager.GetString("Cartel1t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to breve encuesta.
        /// </summary>
        internal static string Cartel1t5 {
            get {
                return ResourceManager.GetString("Cartel1t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (solamente te llevará 10 minutos) o envianos tus comentarios a.
        /// </summary>
        internal static string Cartel1t6 {
            get {
                return ResourceManager.GetString("Cartel1t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Gracias!.
        /// </summary>
        internal static string Cartel1t7 {
            get {
                return ResourceManager.GetString("Cartel1t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Los datos de desmonte generado durante el testeo de la nueva plataforma solamente se usarán internamente, para evaluar y mejorar el nuevo sistema.).
        /// </summary>
        internal static string Cartel1t8 {
            get {
                return ResourceManager.GetString("Cartel1t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalá el plugin the Microsoft Silverlight, sólo lleva unos segundos.
        /// </summary>
        internal static string Cartel1t9 {
            get {
                return ResourceManager.GetString("Cartel1t9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El explorador que estás usando actualmente, Google Chrome o Microsoft Edge, dejó de ser compatible con la tecnología que usa Guardianes. 
        ///                                            Para seguir cuidando nuestros bosques te recomendamos que utilices otros como.
        /// </summary>
        internal static string Cartel2t2 {
            get {
                return ResourceManager.GetString("Cartel2t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin embargo, si no querés cambiar de explorador, podés ayudar probando.
        /// </summary>
        internal static string Cartel2t3 {
            get {
                return ResourceManager.GetString("Cartel2t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía estamos desarrollando esta última versión que emplea las tecnologías web más avanzadas. Te brindaremos una experiencia superior en todos los navegadores, teléfonos móviles y tablets..
        /// </summary>
        internal static string Cartel2t4 {
            get {
                return ResourceManager.GetString("Cartel2t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Después de jugar, por favor, completá nuestra.
        /// </summary>
        internal static string Cartel2t5 {
            get {
                return ResourceManager.GetString("Cartel2t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu opinión es muy importante para poder mejorar la nueva plataforma. ¡Gracias!.
        /// </summary>
        internal static string Cartel2t6 {
            get {
                return ResourceManager.GetString("Cartel2t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrucciones para seguir usando Guardianes en Chrome en versiones anteriores a 45 (septiembre-2015):.
        /// </summary>
        internal static string Cartel3t1 {
            get {
                return ResourceManager.GetString("Cartel3t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribí en la barra de búsqueda: chrome://flags/#enable-npapi.
        /// </summary>
        internal static string Cartel3t2 {
            get {
                return ResourceManager.GetString("Cartel3t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la parte superior de la pantalla, aparecerá una opción bajo el título “Habilitar NPAPI”. Hacé click en “Habilitar”..
        /// </summary>
        internal static string Cartel3t3 {
            get {
                return ResourceManager.GetString("Cartel3t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la parte inferior de la pantalla, hacé click en el botón “Reiniciar Ahora”.
        /// </summary>
        internal static string Cartel3t4 {
            get {
                return ResourceManager.GetString("Cartel3t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Listo! ¡Ya podés continuar cuidando nuestros bosques!.
        /// </summary>
        internal static string Cartel3t5 {
            get {
                return ResourceManager.GetString("Cartel3t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dirección de email.
        /// </summary>
        internal static string LoginEmailHint {
            get {
                return ResourceManager.GetString("LoginEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidaste tu contraseña?.
        /// </summary>
        internal static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se te enviará una nueva contraseña por mail.
        /// </summary>
        internal static string LoginForgotPasswordTitle {
            get {
                return ResourceManager.GetString("LoginForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/guardianes.png.
        /// </summary>
        internal static string LoginGuardiansImage {
            get {
                return ResourceManager.GetString("LoginGuardiansImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresá tu dirección de mail para&lt;br /&gt; comenzar a cuidar el bosque!.
        /// </summary>
        internal static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenés que escribir una dirección de mail válida.
        /// </summary>
        internal static string LoginInvalidEmail {
            get {
                return ResourceManager.GetString("LoginInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o la contraseña son incorrectos.
        /// </summary>
        internal static string LoginInvalidUserOrPass {
            get {
                return ResourceManager.GetString("LoginInvalidUserOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGUIENTE &gt;&gt;.
        /// </summary>
        internal static string LoginNextButton {
            get {
                return ResourceManager.GetString("LoginNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te pedimos que elijas una contraseña para continuar!.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contraseña.
        /// </summary>
        internal static string LoginPasswordHint {
            get {
                return ResourceManager.GetString("LoginPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te hemos enviado un email.
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;
        ///        Lo vas a recibir en pocos minutos. Seguí las instrucciones indicadas en el mail para resetear tu contraseña.
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;
        ///        Si no recibiste el mail, chequeá las carpetas de correo no deseado. Asegurate que los filtros de tu mail acepten mails desde greenpeace.org
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;
        ///        Muchas Gracias..
        /// </summary>
        internal static string LoginPasswordRecoveryMessage {
            get {
                return ResourceManager.GetString("LoginPasswordRecoveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repetir contraseña.
        /// </summary>
        internal static string LoginPasswordRepeatHint {
            get {
                return ResourceManager.GetString("LoginPasswordRepeatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener al menos 5 caracteres..
        /// </summary>
        internal static string LoginPasswordValidationLength {
            get {
                return ResourceManager.GetString("LoginPasswordValidationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        internal static string LoginPasswordValidationMatch {
            get {
                return ResourceManager.GetString("LoginPasswordValidationMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error. No pudimos finalizar la registración. Por favor contacte a un administrador..
        /// </summary>
        internal static string LoginRegistrationFailed {
            get {
                return ResourceManager.GetString("LoginRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMENZAR.
        /// </summary>
        internal static string LoginStartButton {
            get {
                return ResourceManager.GetString("LoginStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardianes - Iniciar Sesion.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este es tu nombre de usuario!.
        /// </summary>
        internal static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click aquí para ver el video.
        /// </summary>
        internal static string LoginVideoTitle {
            get {
                return ResourceManager.GetString("LoginVideoTitle", resourceCulture);
            }
        }
    }
}
